[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests -B"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/v1/actuator/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
